### ISSUE TITLE
Due + MCP 2562 high Voltage output on CAN H + L

### ISSUE THREAD

**Issue by virtuvas** [ttlappalainen/NMEA2000_due#2]
hello Timo,

Have managed to collect a lot of boards, chips and trying various combinations. 
Using a MEGA + NRem canbus shield everything works fine. 
Using a teensy 3.2 or 3.5 + MCP2551 again all is fine.
I'm testing on a Garmin GMI10 as well as in the boat with a lot of Garmin devices.

However, for one of the projects I'd really like to use a Due. Now no mater how hard I've tried, I've had no success using the internal CAN and the MCP2562.

Out of curiosity I tried the two working combinations as well as the Due on the same system (with just powersupply and a GMI10), simply loading the same BatteryMonitor example and using an analogue Multimeter I got the following volt values between CANH and CANL:

Teensy + MCP2552:          around 10mV pulsing a bit
MEGA + Canbus shield:    around 250mV pulsing down to 200mV every 2-3secs
Due + MCP2562:               give over 1V
edit to say that I also tried changing the 2562 supply to 3.3V and I get 600mV but no visible pulsing

Are these values ok? I've just followed your diagram to the letter, even made a second attempt on a prototyping board, no luck!
Teensy and MEGA show up in the device list of the GMI10, Due doesn't appear.
Also tried some of my code, same thing, works on Teensy and MEGA, nothing on Due.

Any ideas?

cheers

Vassilis

**Comment by ttlappalainen** [comment]
I have Due with MCP2562 as also my Teensy boards. So something is missing. Are you sure you have terminator resistors connected? Triple check connections, while it is simple - I have also mixed Tx pins once on MCP2562. MCP2562 requires also pin 5 to be connected to 3.3 V and use 5V for VDD. All as in my schema. Someone also managed to burn MCP2562 - I do not how, since I have also mixed VDD and Vss - just did not work before changing them right.

No more ideas at the moment.

**Comment by virtuvas** [comment]
Timo,

everything was as your drawing (tbh not to many things to do wrong!) simply connected to the Due. 
Tried various things and at one point it simply worked. Then I couldn't reproduce it until I hit the reset button on the Due next to the native USB port.
So it seems that in order to work, I have to fire it up, connected to NMEA2K and THEN hit the reset! 
Am I missing something? 
Can I avoid that step? 
Is it something wrong in my code?

Board is a genuine  Arduino.cc Due R3 board.
Any ideas?

thanks

V.

**Comment by ttlappalainen** [comment]
So if you just have it connected bus and turn it on, it does not work? What code do you mean - BatteryMonitor example?

On my later documents ( e.g. https://github.com/ttlappalainen/NMEA2000/blob/master/Examples/TeensyActisenseListenerSender/Documents/Teensy_Actisense_listener_sender_schematics.pdf) I have used 4.7 kohm resistor to pull STBY (pin 8) to GND instead of direct connection to GND. I do not remember, how do I have it on my DUE device on boat. Please try that.

**Comment by virtuvas** [comment]
SOLVED :)

did what was suggested on this thread https://forum.arduino.cc/index.php?topic=256771.msg2633995#msg2633995 post 47.
So, soldered a 10K resistor, Due R3, starts everytime without a need for a reboot.
Apparently this is a known issue for R3 boards, so anyone using them should do something about it.

Regarding my final board that wasn't working and the high CAN values (not sure related) I had a bad solder between GND (Vss) and pin 8 (STBY). redid it, everything works!

thanks for all the work you've done!

cheers

V.
